"""
Django settings for network_project project.
Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7hafn58b8p341c8=6buj02(s&6yf^!9f3zk^&4lh=79v)!s8r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'network_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'network_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n', # ???????? ???? ????? ??
            ],
        },
    },
]

WSGI_APPLICATION = 'network_project.wsgi.application'


# Database (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'network_db',
        'USER': 'net_admin',
        'PASSWORD': 'StrongPassword123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# =========================================
# Internationalization (??????? ???? ? ?????)
# =========================================
LANGUAGE_CODE = 'en'
TIME_ZONE = 'Asia/Kabul'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('fa', _('Persian')),
    ('en', _('English')),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
# =========================================
# Static files (???????? ???? ?? runserver)
# =========================================
STATIC_URL = '/static/'

# ?? ???? ?????? ???????? ???? ?? ??? ???? ?? ?? ????
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# ???? STATIC_ROOT ?? ???? ???? ???????? ??????? ?????? (?? runserver ???? ????)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# =========================================
# Email & Auth
# =========================================
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# =========================================
# Celery & Redis Settings
# =========================================
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


# =========================================
# Jazzmin Admin Panel Settings
# =========================================
JAZZMIN_SETTINGS = {
    "site_title": "Network Admin",
    "site_header": "Network Management",
    "site_brand": "Inventory System",
    "welcome_sign": "?? ??? ?????? ????????? ???? ??? ?????",
    "site_logo": None,
    "copyright": "Network Management System",
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "network_app.Device": "fas fa-laptop-network",
        "network_app.BTS": "fas fa-broadcast-tower",
        "network_app.Province": "fas fa-map-marker-alt",
    },
    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_ui_builder": False, 
    
    # ???? ???? CSS ?????? ?????
    "custom_css": "css/admin_custom.css",
    "default_theme_mode": "dark",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera",
    "sidebar": "sidebar-dark-success",
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}