# Generated by Django 6.1 on 2026-08-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='??? ??? (BTS)')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco')], max_length=20)),
                ('command_order', models.IntegerField(default=1, verbose_name='????? ????')),
                ('command_text', models.TextField(verbose_name='??? ?????')),
                ('is_active', models.BooleanField(default=True, verbose_name='????')),
            ],
            options={
                'ordering': ['command_order'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='??? ?????')),
                ('mt_user', models.CharField(max_length=100, verbose_name='???? ????????')),
                ('mt_pass', models.CharField(max_length=100, verbose_name='????? ????????')),
                ('cisco_user', models.CharField(max_length=100, verbose_name='???? ?????')),
                ('cisco_pass', models.CharField(max_length=100, verbose_name='????? ?????')),
                ('mt_port', models.IntegerField(default=3100, verbose_name='???? ????????')),
                ('cisco_port', models.IntegerField(default=22, verbose_name='???? ?????')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_run_config', '???????? ?????? ???? ???'), ('can_view_reports', '???????? ???????? ?? ?????'), ('can_search_mac', '???????? ?????? ?? ????? ???'), ('can_check_signal', '???????? ?????? ????????? ?? ?????')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='????? ??????')),
                ('device_type', models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco Switch')], max_length=20, verbose_name='??? ??????')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='?? ????')),
                ('bts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='network_app.bts')),
            ],
        ),
        migrations.AddField(
            model_name='bts',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bts_list', to='network_app.province'),
        ),
    ]
