# Generated by Django 6.1 on 2026-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'permissions': [('can_run_config', 'Can run config'), ('can_view_reports', 'Can view reports'), ('can_search_mac', 'Can search MAC'), ('can_check_signal', 'Can check signals')]},
        ),
        migrations.AddField(
            model_name='device',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='device',
            name='mikrotik_model',
            field=models.CharField(blank=True, choices=[('qrt5', 'QRT 5'), ('lhg', 'LHG'), ('sxt6', 'SXT 6'), ('relink', 'RE-link (Inventory Only)')], max_length=20, null=True, verbose_name='MikroTik Model'),
        ),
        migrations.AddField(
            model_name='device',
            name='ssid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SSID'),
        ),
        migrations.AlterField(
            model_name='bts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='BTS Name'),
        ),
        migrations.AlterField(
            model_name='configcommand',
            name='command_order',
            field=models.IntegerField(default=1, verbose_name='Execution Order'),
        ),
        migrations.AlterField(
            model_name='configcommand',
            name='command_text',
            field=models.TextField(verbose_name='Command Text'),
        ),
        migrations.AlterField(
            model_name='configcommand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco Switch')], max_length=20, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=50, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='province',
            name='cisco_pass',
            field=models.CharField(max_length=100, verbose_name='Cisco Password'),
        ),
        migrations.AlterField(
            model_name='province',
            name='cisco_port',
            field=models.IntegerField(default=22, verbose_name='Cisco Port'),
        ),
        migrations.AlterField(
            model_name='province',
            name='cisco_user',
            field=models.CharField(max_length=100, verbose_name='Cisco User'),
        ),
        migrations.AlterField(
            model_name='province',
            name='mt_pass',
            field=models.CharField(max_length=100, verbose_name='MikroTik Password'),
        ),
        migrations.AlterField(
            model_name='province',
            name='mt_port',
            field=models.IntegerField(default=3100, verbose_name='MikroTik Port'),
        ),
        migrations.AlterField(
            model_name='province',
            name='mt_user',
            field=models.CharField(max_length=100, verbose_name='MikroTik User'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Province Name'),
        ),
    ]
