# Generated by Django 6.1 on 2026-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0002_alter_activitylog_options_device_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco Switch'), ('relink', 'RE-link (Inventory Only)')], max_length=20, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mikrotik_model',
            field=models.CharField(blank=True, choices=[('qrt5', 'QRT 5'), ('lhg', 'LHG'), ('sxt6', 'SXT 6')], max_length=20, null=True, verbose_name='MikroTik Model'),
        ),
    ]
