# Generated by Django 6.1 on 2026-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0003_alter_device_device_type_alter_device_mikrotik_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='relink_model',
            field=models.CharField(blank=True, choices=[('xc6', 'XC6'), ('xc7', 'XC7')], max_length=20, null=True, verbose_name='RE-link Model'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco Switch'), ('relink', 'RE-link')], max_length=20, verbose_name='Device Type'),
        ),
    ]
