# Generated by Django 6.1 on 2026-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0004_device_relink_model_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Device Name'),
        ),
    ]
