# Generated by Django 6.1 on 2026-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0005_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='has_poe',
            field=models.BooleanField(default=False, verbose_name='POE Adapter'),
        ),
    ]
