# Generated by Django 6.1 on 2026-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0006_device_has_poe'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='has_adapter',
            field=models.BooleanField(default=False, verbose_name='Adapter'),
        ),
        migrations.AlterField(
            model_name='device',
            name='has_poe',
            field=models.BooleanField(default=False, verbose_name='POE'),
        ),
    ]
