# Generated by Django 6.1 on 2026-08-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0007_device_has_adapter_alter_device_has_poe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mikrotik_model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='relink_model',
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(blank=True, choices=[('qrt5', 'QRT 5 (MikroTik)'), ('lhg', 'LHG (MikroTik)'), ('sxt6', 'SXT 6 (MikroTik)'), ('xc6', 'XC6 (RE-link)'), ('xc7', 'XC7 (RE-link)')], max_length=20, null=True, verbose_name='Device Model'),
        ),
    ]
