# Generated by Django 6.1 on 2026-08-14 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0008_remove_device_mikrotik_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='??? ??????')),
                ('commands', models.TextField(verbose_name='???????')),
                ('device_type', models.CharField(default='mikrotik', max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='???? ????')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
