# Generated by Django 6.1 on 2026-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0009_commandhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='description',
            field=models.CharField(max_length=255, verbose_name='???????'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.CharField(blank=True, choices=[('QRT', 'QRT (MikroTik)'), ('LHG', 'LHG (MikroTik)'), ('Sector', 'Sector (MikroTik)'), ('SXT6', 'SXT 6 (MikroTik)'), ('CCR1009', 'CCR1009 (MikroTik)'), ('SXT', 'SXT (MikroTik)'), ('qrt5', 'QRT 5 (Old)'), ('X6', 'XC6 (RE-link)'), ('X7', 'XC7 (RE-link)'), ('LDF', 'LDF (RE-link)'), ('xc6', 'XC6 (Old)'), ('xc7', 'XC7 (Old)'), ('2960', 'Cisco 2960')], max_length=20, null=True, verbose_name='Device Model'),
        ),
    ]
