# Generated by Django 6.1 on 2026-08-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0010_alter_commandhistory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed')], default='Pending', max_length=20, verbose_name='?????'),
        ),
    ]
