# Generated by Django 6.1 on 2026-08-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0011_commandhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='prov_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='???? ????? ??????'),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='target_ips',
            field=models.TextField(blank=True, null=True, verbose_name='????????? ??? (?? ???? ??? ???)'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='???? ?????'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Running', 'Running'), ('Done', 'Done'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending Approval', max_length=30, verbose_name='?????'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='????')),
                ('is_read', models.BooleanField(default=False, verbose_name='?????? ???')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='network_app.commandhistory')),
            ],
        ),
    ]
