# Generated by Django 6.1 on 2026-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0012_commandhistory_prov_id_commandhistory_target_ips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandhistory',
            name='prov_id',
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='???? ????'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Done', 'Done'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='target_ips',
            field=models.TextField(blank=True, null=True, verbose_name='????????? ???'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
