# Generated by Django 6.1 on 2026-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0013_remove_commandhistory_prov_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='output_log',
            field=models.TextField(blank=True, null=True, verbose_name='??? ?????'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='?????'),
        ),
    ]
