# Generated by Django 6.1 on 2026-08-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0014_commandhistory_output_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='commands',
            field=models.TextField(verbose_name='دستورات'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان اجرا'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='output_log',
            field=models.TextField(blank=True, null=True, verbose_name='لاگ خروجی'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='target_ips',
            field=models.TextField(blank=True, null=True, verbose_name='آی\u200cپی\u200cهای هدف'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Password')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
