# Generated by Django 6.1 on 2026-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0015_alter_commandhistory_commands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_password',
        ),
        migrations.AddField(
            model_name='profile',
            name='receiver_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Receiver Password'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sender_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Password'),
        ),
    ]
