# Generated by Django 6.1 on 2026-08-19 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0016_remove_profile_device_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receiver_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sender_password',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Password'),
        ),
        migrations.CreateModel(
            name='UserProvinceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender Username')),
                ('sender_pass', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Password')),
                ('receiver_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Receiver Username')),
                ('receiver_pass', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receiver Password')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_app.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'province')},
            },
        ),
    ]
