# Generated by Django 6.1 on 2026-08-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0017_remove_profile_receiver_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprovincecredential',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='userprovincecredential',
            name='sender_user',
        ),
    ]
