# Generated by Django 6.1 on 2026-08-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0018_remove_userprovincecredential_receiver_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='آی\u200cپی دستگاه')),
                ('device_type', models.CharField(max_length=20, verbose_name='نوع دستگاه (سندر/ریسیور)')),
                ('is_online', models.BooleanField(default=False, verbose_name='وضعیت پینگ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان اتصال')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_app.province', verbose_name='ولایت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
