# Generated by Django 6.1 on 2026-08-19 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0019_connectionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bts',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='bts',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='completed_devices',
            field=models.IntegerField(default=0, verbose_name='Completed Devices'),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='progress_percentage',
            field=models.IntegerField(default=0, verbose_name='Progress Percentage'),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='total_devices',
            field=models.IntegerField(default=0, verbose_name='Total Devices'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='commands',
            field=models.TextField(verbose_name='Commands'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Execution Time'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='output_log',
            field=models.TextField(blank=True, null=True, verbose_name='Output Log'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='target_ips',
            field=models.TextField(blank=True, null=True, verbose_name='Target IPs'),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='device_type',
            field=models.CharField(max_length=20, verbose_name='Device Type (Sender/Receiver)'),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='ip_address',
            field=models.CharField(max_length=50, verbose_name='Device IP'),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Ping Status'),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_app.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Connection Time'),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
