# Generated by Django 6.1 on 2026-08-20 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0020_bts_latitude_bts_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('wireless', 'Wireless (Microwave/Radio)'), ('fiber', 'Fiber Optic')], default='wireless', max_length=20, verbose_name='Link Type')),
                ('capacity_mbps', models.IntegerField(default=1000, help_text='Total link capacity in Mbps', verbose_name='Capacity (Mbps)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('source_bts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='network_app.bts', verbose_name='Source BTS')),
                ('target_bts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='network_app.bts', verbose_name='Target BTS')),
            ],
        ),
    ]
