# Generated by Django 6.1 on 2026-08-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0021_networklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='current_rx_mbps',
            field=models.FloatField(default=0.0, verbose_name='Current RX (Mbps)'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='current_tx_mbps',
            field=models.FloatField(default=0.0, verbose_name='Current TX (Mbps)'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='last_snmp_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last SNMP Update'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='source_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_device_links', to='network_app.device', verbose_name='Source Device (For SNMP)'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='source_interface',
            field=models.CharField(blank=True, help_text='e.g., ether1, sfp1', max_length=100, null=True, verbose_name='Source Interface'),
        ),
        migrations.AddField(
            model_name='province',
            name='snmp_community',
            field=models.CharField(default='public', max_length=50, verbose_name='SNMP Community'),
        ),
    ]
