# Generated by Django 6.1 on 2026-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0022_networklink_current_rx_mbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='snmp_community',
            field=models.CharField(default='public', max_length=50, verbose_name='SNMP Community'),
        ),
        migrations.AlterField(
            model_name='province',
            name='snmp_community',
            field=models.CharField(default='public', max_length=50, verbose_name='Default SNMP Community'),
        ),
    ]
