# Generated by Django 6.1 on 2026-08-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0023_networklink_snmp_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='link_ip_network',
            field=models.CharField(blank=True, help_text='e.g., 10.10.10.0/30', max_length=50, null=True, verbose_name='Link IP / Subnet'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='target_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_device_links', to='network_app.device', verbose_name='Target Device'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='target_interface',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Interface'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='target_snmp_community',
            field=models.CharField(default='public', max_length=50, verbose_name='Target SNMP Community'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='snmp_community',
            field=models.CharField(default='public', max_length=50, verbose_name='Source SNMP Community'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='source_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_device_links', to='network_app.device', verbose_name='Source Device'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='source_interface',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source Interface'),
        ),
    ]
