# Generated by Django 6.1 on 2026-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0024_networklink_link_ip_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networklink',
            name='source_device',
        ),
        migrations.RemoveField(
            model_name='networklink',
            name='target_device',
        ),
        migrations.AddField(
            model_name='networklink',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='target_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Target IP'),
        ),
    ]
