# Generated by Django 6.1 on 2026-08-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0025_remove_networklink_source_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networklink',
            name='link_ip_network',
        ),
    ]
