# Generated by Django 6.1 on 2026-08-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0026_remove_networklink_link_ip_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='source_device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco'), ('ubiquiti', 'Ubiquiti'), ('mimosa', 'Mimosa'), ('huawei', 'Huawei'), ('other', 'Other')], default='mikrotik', max_length=50),
        ),
        migrations.AddField(
            model_name='networklink',
            name='target_device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco'), ('ubiquiti', 'Ubiquiti'), ('mimosa', 'Mimosa'), ('huawei', 'Huawei'), ('other', 'Other')], default='mikrotik', max_length=50),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='capacity_mbps',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='current_rx_mbps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='current_tx_mbps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='last_snmp_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='link_type',
            field=models.CharField(choices=[('Fiber Optic', 'Fiber Optic'), ('Microwave', 'Microwave/Radio'), ('Wireless', 'Wireless (P2P/P2mP)'), ('Ethernet', 'Ethernet/Copper')], max_length=50),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='snmp_community',
            field=models.CharField(default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='source_bts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='network_app.bts'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='source_interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='source_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='target_bts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='network_app.bts'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='target_interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='target_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='target_snmp_community',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
